# Offense count: 26
Metrics/AbcSize:
  Max: 84

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 9

# Offense count: 23
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 48

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 11

# Offense count: 10
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 12
Style/Documentation:
  Enabled: false

# Offense count: 14
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 6
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

